import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, CheckCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

import { EmptyState } from "@/components/ui/States";
import { notificationsApi } from "@/services/notificationsApi";
import { formatDateTime } from "@/utils/format";
import { cn } from "@/utils/cn";

export function NotificationBell({ viewAllHref }: { viewAllHref?: string }) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const queryClient = useQueryClient();

  const { data: unread } = useQuery({
    queryKey: ["notifications", "unread-count"],
    queryFn: notificationsApi.unreadCount,
    refetchInterval: 60_000,
  });

  const { data: recent } = useQuery({
    queryKey: ["notifications", "recent"],
    queryFn: () => notificationsApi.list({ page_size: 8 }),
    enabled: open,
  });

  useEffect(() => {
    function onClickOutside(event: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, []);

  async function markAllRead() {
    await notificationsApi.markAllRead();
    void queryClient.invalidateQueries({ queryKey: ["notifications"] });
  }

  const count = unread?.unread_count ?? 0;

  return (
    <div className="relative" ref={containerRef}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={`${t("nav.notifications")}${count > 0 ? `, ${count}` : ""}`}
        className="relative rounded-lg p-2 text-ink-muted hover:bg-canvas hover:text-ink"
      >
        <Bell size={20} />
        {count > 0 && (
          <span className="absolute right-1 top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-status-danger px-1 text-[10px] font-semibold text-white">
            {count > 99 ? "99+" : count}
          </span>
        )}
      </button>

      {open && (
        <div className="absolute right-0 z-40 mt-2 w-80 rounded-xl border border-line bg-surface shadow-card">
          <div className="flex items-center justify-between border-b border-line px-4 py-3">
            <p className="text-sm font-semibold text-ink">{t("nav.notifications")}</p>
            <button
              type="button"
              onClick={() => void markAllRead()}
              className="flex items-center gap-1 text-xs font-medium text-brand hover:text-brand-hover"
            >
              <CheckCheck size={14} />
              {t("notifications.markAllRead")}
            </button>
          </div>
          <div className="max-h-96 overflow-y-auto">
            {!recent || recent.items.length === 0 ? (
              <EmptyState title={t("notifications.noNotifications")} description={t("notifications.allCaughtUp")} />
            ) : (
              <ul>
                {recent.items.map((notification) => (
                  <li
                    key={notification.id}
                    className={cn("border-b border-line px-4 py-3 last:border-0", !notification.is_read && "bg-brand-light/40")}
                  >
                    {/* Title/message are generated by the backend in English and are
                        not yet translated - see the Stage 7 summary for why. */}
                    <p className="text-sm font-medium text-ink">{notification.title}</p>
                    <p className="mt-0.5 text-sm text-ink-muted">{notification.message}</p>
                    <p className="mt-1 font-mono text-xs text-ink-faint">{formatDateTime(notification.created_at)}</p>
                  </li>
                ))}
              </ul>
            )}
          </div>
          {viewAllHref && (
            <Link
              to={viewAllHref}
              onClick={() => setOpen(false)}
              className="block border-t border-line px-4 py-2.5 text-center text-sm font-medium text-brand hover:bg-canvas"
            >
              {t("notifications.viewAll")}
            </Link>
          )}
        </div>
      )}
    </div>
  );
}
